import Head from "next/head";
import type { GetStaticProps, NextPage } from "next";
import { getMarkdownPaths } from "../utils/getMarkdownPaths";
import Link from "next/link";
import Layout from "@/components/Layout";

interface HomeProps {
  paths: string[];
}

const Home: NextPage<HomeProps> = ({ paths }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        index page
        <ul>
          {paths.map((path) => (
            <li key={path}>
              <Link href={path}>{path}</Link>
            </li>
          ))}
        </ul>
      </Layout>
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async (_context) => {
  // get route paths from /markdown
  const paths = getMarkdownPaths();

  return {
    props: {
      paths,
    },
  };
};
